# Generated by Django 5.1.4 on 2025-01-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('birth_weight', models.FloatField()),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('from_age', models.IntegerField()),
                ('to_age', models.IntegerField()),
                ('question_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_education', models.CharField(max_length=255)),
                ('father_education', models.CharField(max_length=255)),
                ('living_area', models.CharField(max_length=255)),
                ('father_profession', models.CharField(max_length=255)),
                ('mother_profession', models.CharField(max_length=255)),
                ('father_monthly_income', models.FloatField()),
                ('number_of_siblings', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='patients.question')),
            ],
        ),
    ]
