# Generated by Django 5.1.4 on 2025-01-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RndaResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_date_of_assessment', models.DateField()),
                ('assessment_number', models.IntegerField()),
                ('rnda_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rnda_score_text', models.CharField(max_length=155)),
                ('rnda_domain', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.patient')),
            ],
        ),
    ]
